public class AwesomeCalculator {
    /*
    public static Double add(Double x, Double y) {
        calculatorServicesTesting.CalculatorImplPort calculator = 
            new calculatorServicesTesting.CalculatorImplPort();
        return calculator.doAdd(x,y);
    }
    public static Double divide(Double x, Double y) {
        calculatorServicesTesting.CalculatorImplPort calculator = 
            new calculatorServicesTesting.CalculatorImplPort();
        return calculator.doDivide(x,y);
    }
    public static Double substract(Double x, Double y) {
        calculatorServicesTesting.CalculatorImplPort calculator = 
            new calculatorServicesTesting.CalculatorImplPort();
        return calculator.doSubtract(x,y);
    }
    public static Double doMultiply(Double x, Double y) {
        calculatorServicesTesting.CalculatorImplPort calculator = 
            new calculatorServicesTesting.CalculatorImplPort();
        return calculator.doAdd(x,y);
    }
*/
}